[2021-09-30 10:30:30] WARNING 1128:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 10:38:23] WARNING 5892:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 10:38:49] WARNING 16648:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 10:39:35] WARNING 12400:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 10:39:49] ERROR 12400:[app.py:1454] - Exception on /v1/air/setCollectScheduler [GET]
Traceback (most recent call last):
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'test.get1' did not return a valid response. The function either returned None or ended without a return statement.
[2021-09-30 10:41:16] WARNING 14420:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 10:47:15] WARNING 16260:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 10:51:45] WARNING 17264:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 10:53:43] WARNING 15912:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 10:56:32] WARNING 6776:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 11:00:23] WARNING 16812:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 11:06:04] WARNING 3144:[base.py:120] - Run time of job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 11:05:34 CST)" was missed by 0:00:30.351439
[2021-09-30 11:06:04] WARNING 3144:[base.py:120] - Run time of job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 11:06:09 CST)" was missed by 0:00:25.352444
[2021-09-30 11:06:04] WARNING 3144:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 11:06:04] WARNING 3144:[base.py:120] - Run time of job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 11:06:09 CST)" was missed by 0:00:20.354418
[2021-09-30 11:06:04] WARNING 3144:[base.py:120] - Run time of job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 11:06:09 CST)" was missed by 0:00:15.355399
[2021-09-30 11:06:04] WARNING 3144:[base.py:120] - Run time of job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 11:06:09 CST)" was missed by 0:00:10.355399
[2021-09-30 11:06:04] WARNING 3144:[base.py:120] - Run time of job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 11:06:09 CST)" was missed by 0:00:05.356413
[2021-09-30 11:07:04] WARNING 17764:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 11:15:09] ERROR 1136:[core.py:152] - __init__() got an unexpected keyword argument 'interval'
[2021-09-30 11:15:09] WARNING 1136:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 11:15:45] ERROR 12844:[core.py:152] - 'Job identifier (collect) conflicts with an existing job'
[2021-09-30 11:15:45] WARNING 12844:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 11:16:32] WARNING 3448:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 11:17:51] WARNING 18168:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 11:17:56] ERROR 18168:[base.py:131] - Job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 11:18:01 CST)" raised an exception
Traceback (most recent call last):
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "G:\technology\AirPi\back_python\app\Air\CollectData.py", line 9, in collect
    path = current_app['SQLITE_PATH']
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\werkzeug\local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\werkzeug\local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\flask\globals.py", line 47, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
[2021-09-30 11:18:01] ERROR 18168:[base.py:131] - Job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 11:18:06 CST)" raised an exception
Traceback (most recent call last):
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "G:\technology\AirPi\back_python\app\Air\CollectData.py", line 9, in collect
    path = current_app['SQLITE_PATH']
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\werkzeug\local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\werkzeug\local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\flask\globals.py", line 47, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
[2021-09-30 11:18:06] ERROR 18168:[base.py:131] - Job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 11:18:11 CST)" raised an exception
Traceback (most recent call last):
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "G:\technology\AirPi\back_python\app\Air\CollectData.py", line 9, in collect
    path = current_app['SQLITE_PATH']
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\werkzeug\local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\werkzeug\local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\flask\globals.py", line 47, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
[2021-09-30 11:22:26] WARNING 17480:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 13:21:09] WARNING 8424:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 13:22:15] WARNING 15704:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 14:27:09] WARNING 15264:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 14:31:38] WARNING 5588:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 14:31:54] WARNING 15952:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 14:32:18] WARNING 9200:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 14:42:22] WARNING 17876:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 15:28:32] WARNING 13104:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 15:29:11] WARNING 18416:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 15:29:42] WARNING 3580:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 15:44:26] WARNING 11088:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 15:44:31] ERROR 11088:[base.py:131] - Job "collect (trigger: interval[0:00:05], next run at: 2021-09-30 15:44:36 CST)" raised an exception
Traceback (most recent call last):
  File "G:\technology\AirPi\back_python\venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "G:\technology\AirPi\back_python\app\Air\CollectData.py", line 17, in collect
    sql.insert({
  File "G:\technology\AirPi\back_python\util\sql_factory.py", line 22, in insert
    for k, v in data.items():
AttributeError: 'str' object has no attribute 'items'
[2021-09-30 15:45:00] WARNING 5088:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 15:45:31] WARNING 5680:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-09-30 15:47:25] WARNING 15440:[_internal.py:225] -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
